from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('bsht.cgi-bin',
    # Example:
    # (r'^bsht/', include('bsht.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/(.*)', admin.site.root),
	(r'^$','admin.index'),
	#(r'^javascripts/(?P<path>.*)$','django.views.static.serve', {'document_root':'./javascripts'}),
	(r'^sign_in/','admin.sign_in'),
	(r'^check_sign_in/','admin.check_sign_in'),
	(r'^change_capacity$','admin.change_capacity'),
	(r'^save_capacity$','admin.save_capacity'),
	(r'^change_passwd/','admin.change_passwd'),
	(r'^sign_out/','admin.sign_out'),
	(r'^monitor_sign_out/','admin.monitor_sign_out'),
	(r'^monitor_user/','admin.get_monitor_user'),
	(r'^save_monitor_user/','admin.set_monitor_user'),
	(r'^netconf/save','admin.netconf_save'),
	(r'^netconf/$','admin.netconf_read'),
	(r'^reboot/','admin.reboot'),
	(r'^monitor$','monitor.index'),
	(r'^monitor1$','monitor.index1'),
	(r'^dialog$','monitor.dialog'),
	(r'^spots$','spots.index'),
	(r'^spots/states$','spots.states'),
	(r'^spots/save$','spots.save'),
	(r'^spots/backup$','spots.backup'),
	(r'^spots/restore$','spots.restore'),
	(r'^devices/save$','devices.save'),
	(r'^devices/save_spot$','devices.save_spot'),
	(r'^devices/remove$','devices.remove'),
	(r'^devices/remove_spot$','devices.remove_spot'),
        (r'^devices/import_spots$','devices.import_spots'),
        (r'^spots/all$','spots.all'),
	(r'^spots/list$','spots.list'),
	(r'^monitor/spots$','monitor.spots'),
	(r'^monitor1/spots$','monitor.spots1'),
	(r'^spots/(?P<id>\w+)/$','spots.get_spot'),
	(r'^spots/remove$','spots.remove'),
	(r'^gateway/get_dictionary$','gateway.get_dictionary'),
	(r'^gateway/list_gis$','gateway.list_gis'),
	(r'^gateway/config$','gateway.config'),
	(r'^gateway/add_gis$','gateway.add_gis'),
	(r'^gateway/remove_gis$','gateway.remove_gis'),
	(r'^gateway/update_gis$','gateway.update_gis'),
	(r'^gateway/all$','gateway.all'),
	(r'^gateway/register$','gateway.register'),
	(r'^gateway/get_inf$','gateway.get_inf'),
	(r'^gateway/get_devices$','gateway.get_devices'),
	(r'^gateway/save$','gateway.save'),
        (r'^gateway/get_config$','gateway.get_config'),
        (r'^gateway/get_remote_conf$','gateway.get_remote_conf'),
	(r'^net/read$','net.read'),
	(r'^meeting$','meeting.index'),
	(r'^meeting/decoder/list$','meeting.decoder_list'),
	(r'^meeting/decoder/save$','meeting.decoder_save'),
	(r'^meeting/decoder/destroy$','meeting.decoder_destroy'),
	(r'^meeting/venue/list$','meeting.venue_list'),
	(r'^meeting/venue/save$','meeting.venue_save'),
	(r'^meeting/venue/add_device$','meeting.add_device'),
	(r'^meeting/venue/add_encoder$','meeting.add_encoder'),
	(r'^meeting/venue/add_decoder$','meeting.add_decoder'),
	(r'^meeting/venue/destroy$','meeting.remove_venue'),
	(r'^meeting/venue/remove_device$','meeting.remove_device'),
	(r'^meeting/venue/remove_encoder$','meeting.remove_encoder'),
	(r'^meeting/venue/remove_decoder$','meeting.remove_decoder'),
	(r'^meeting/conference/inf$','meeting.conference_inf'),
	(r'^meeting/conference/set_state$','meeting.conference_set_state'),
	(r'^meeting/conference/save$','meeting.conference_save'),
	(r'^drivers/update$','gateway.driver_update'),
	(r'^drivers/add$','gateway.driver_add'),
	(r'^dictionary/add$','gateway.dict_add'),
	(r'^dictionary/update$','gateway.dict_update'),
	(r'^routes/list$','route.list'),
	(r'^routes/save$','route.save'),
	(r'^backup/save$','backup.save'),
	(r'^backup/ishost$','backup.ishost'),
	(r'^backup/switch_server$','backup.switch_server'),
	(r'^backup/read$','backup.read'),
	(r'^backup/do$','backup.do'),
	(r'^upgrade/ver$','upgrade.ver'),
	(r'^upgrade/do$','upgrade.do'),
	(r'^upgrade/ping$','upgrade.ping'),
	(r'^upgrade/check$','upgrade.check'),
	(r'^record_conf/read$','record_conf.read'),
	(r'^record_conf/test$','record_conf.test'),
	(r'^record_conf/save$','record_conf.save'),
	(r'^apply_setting$','admin.apply_setting'),
        (r'^language$','admin.get_language'),
        (r'^record_schedule/create_weekly$','record_schedule.create_weekly'),
        (r'^record_schedule/update_weekly$','record_schedule.update_weekly'),
        (r'^record_schedule/remove_weekly$','record_schedule.remove_weekly'),
        (r'^record_schedule/remove_weeklies$','record_schedule.remove_weeklies'),
        (r'^record_schedule/weeklies$','record_schedule.weeklies'),
        (r'^record_schedule/create_daily$','record_schedule.create_daily'),
        (r'^record_schedule/update_daily$','record_schedule.update_daily'),
        (r'^record_schedule/remove_daily$','record_schedule.remove_daily'),
        (r'^record_schedule/remove_dailies$','record_schedule.remove_dailies'),
        (r'^record_schedule/dailies$','record_schedule.dailies'),
        (r'^record_schedule/record_files$','record_schedule.record_files'),
        (r'^log$','log.view'),
        (r'^crossdomain.xml$','admin.crossdomain')
)
